-- CHALLENGE 1

SELECT A.AU_ID AS AUTHORID, AU_LNAME AS LASTNAME, AU_FNAME AS FIRSTNAME, TITLE, PUB_NAME AS PUBLISHER
FROM TITLES AS T
LEFT JOIN TITLEAUTHOR AS TA
ON T.TITLE_ID = TA.TITLE_ID
INNER JOIN AUTHORS AS A
ON A.AU_ID = TA.AU_ID
LEFT JOIN PUBLISHERS AS P
ON P.PUB_ID = T.PUB_ID;


-- CHALLENGE 2

SELECT A.AU_ID AS AUTHORID, AU_LNAME AS LASTNAME, AU_FNAME AS FIRSTNAME, PUB_NAME AS PUBLISHER, COUNT(TITLE) AS TITLE_COUNT
FROM TITLES AS T
LEFT JOIN TITLEAUTHOR AS TA
ON T.TITLE_ID = TA.TITLE_ID
INNER JOIN AUTHORS AS A
ON A.AU_ID = TA.AU_ID
LEFT JOIN PUBLISHERS AS P
ON P.PUB_ID = T.PUB_ID
GROUP BY A.AU_ID, P.PUB_ID
ORDER BY TITLE_COUNT DESC , A.AU_ID DESC;


-- CHALLENGE 3 

SELECT A.AU_ID AS AUTHORID, A.AU_LNAME AS LASTNAME, A.AU_FNAME AS FIRSTNAME, SUM(S.QTY) AS TOTAL
FROM AUTHORS AS A
INNER JOIN TITLEAUTHOR AS TA
ON A.AU_ID =TA.AU_ID
INNER JOIN TITLES AS T
ON TA.TITLE_ID=T.TITLE_ID
INNER JOIN SALES AS S 
ON T.TITLE_ID=S.TITLE_ID
GROUP BY A.AU_ID, A.AU_LNAME, A.AU_FNAME
ORDER BY TOTAL DESC
LIMIT 5;  -- LIMIT 5 PORQUE TRES PERSONAS HAN VENDIDO 50


-- CHALLENGE 4

SELECT A.AU_ID AS AUTHORID, A.AU_LNAME AS LASTNAME, A.AU_FNAME AS FIRSTNAME, COALESCE(SUM(S.QTY),0) AS TOTAL
FROM AUTHORS AS A
LEFT JOIN TITLEAUTHOR AS TA
ON A.AU_ID =TA.AU_ID
LEFT JOIN TITLES AS T
ON TA.TITLE_ID=T.TITLE_ID
LEFT JOIN SALES AS S 
ON T.TITLE_ID=S.TITLE_ID
GROUP BY A.AU_ID, A.AU_LNAME, A.AU_FNAME
ORDER BY TOTAL DESC;